orbs:
  stackhawk: stackhawk/stackhawk@1.0.2
version: 2.1
workflows:
  scan-local:
    jobs:
      - stackhawk/hawkscan-local:
          app-id: c75c2985-e8eb-4243-9d73-7c9a2c10807f
          env: "${CIRCLE_BRANCH}"
          docker-network: scan_net
          host: http://nginx_test
          steps:
            - run:
                name: Create scan_net Network
                command: docker network create scan_net
            - run:
                name: Run Local Test Instance, nginx_test, on the scan_net Network
                command: docker run --rm --detach -p 8080:80 --name nginx_test nginx
