version: 2.1

commands:
  run-stackhawk:
    parameters:
      configs:
        description: HawkScan configuration files as a space-separated list
        type: string
        default: "stackhawk.yml"
    steps:
      - run:
          name: run stackhawk
          command: |
            cd /zap
            shawk << parameters.configs >>

jobs:
  scan-backend-service-stg:
    docker:
      - image: stackhawk/hawkscan:latest
    environment:
      ENV_NAME: "ci"
    resource_class: small
    steps:
      - run:
          name: Set HawkScan environment variables
          command: |
            echo 'export API_KEY=${HAWK_API_KEY}' >> $BASH_ENV
            echo 'export REPO_DIR=$(pwd)' >> $BASH_ENV
            source $BASH_ENV
      - checkout
      - run-stackhawk:
          configs: backend-service/stackhawk.yml


workflows:
  hawkscan-test:
    jobs:
      - scan-backend-service-stg
