version: 2.1

commands:
  run-stackhawk:
    parameters:
      target_app_name:
        type: string
        default: ""
#       repo_dir:
#         type: string
#         default: ""
      api_key:
        type: string
        default: ""
    steps:
      - run:
          name: run stackhawk
          command: |
            echo "REPO_DIR: ${REPO_DIR}"
            echo "API_KEY: ${API_KEY}"
#            ls << parameters.repo_dir >>
            cd ./<< parameters.target_app_name >>
            shawk stackhawk.yml

jobs:
  extract-hawk:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Run some diagnostics
          command: |
            pwd
            ls
            env
      - persist_to_workspace:
          root: .
          paths:
            - .

  scan-backend-service-stg:
    docker:
      - image: stackhawk/hawkscan:latest
    environment:
      ENV_NAME: "ci"
      REPO_DIR: "/home/zap/workspace"
      API_KEY: $HAWK_API_KEY
      REPO_DIR: $CIRCLE_WORKING_DIRECTORY
    resource_class: small
    steps:
#       - run:
#           name: Create $REPO_DIR
#           command: mkdir -p $REPO_DIR
#       - attach_workspace:
#           at: $REPO_DIR
      - run:
          name: Run some diagnostics
          command: |
            pwd
            ls
            env
      - attach_workspace:
          at: .
      - run:
          name: Run more diagnostics
          command: |
            pwd
            ls
            env
      - run-stackhawk:
          target_app_name: backend-service
          repo_dir: $REPO_DIR
          api_key: $HAWK_API_KEY    # secret variable configured for this repo in CircleCI
          
workflows:
  hawkscan-test:
    jobs:
     - extract-hawk
     - scan-backend-service-stg:
         requires:
           - extract-hawk
