orbs:
  stackhawk: stackhawk/stackhawk@1.0.2
version: 2.1
workflows:
  scan-local:
    jobs:
      - stackhawk/hawkscan-local:
          docker-network: host
          steps:
            - run:
                name: Create scan_net Network
                command: docker network create scan_net
            - run:
                name: Run Local Test Instance, nginx_test, on the scan_net Network
                command: docker run --rm --detach -p 8080:80 --name nginx_test nginx
            - run:
                name: Confidence check scan local
                command: curl http://localhost:8080
