spec:
  template:
    spec:
      volumes:
        - name: initdb
          emptyDir: {}

      initContainers:
        - name: postgres-init
          image: amazon/aws-cli
          command: ["aws"]
          args:
            - s3
            - cp
            - "s3://backups.sandbox.stackhawk.com/devkube/zconger/postgres/beak.sql"
            - /docker-entrypoint-initdb.d/
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: init-dir

      containers:
      - name: postgres-beak
        volumeMounts:
          - mountPath: /docker-entrypoint-initdb.d
            name: init-dir
      serviceAccountName: devkube-db

#      restartPolicy: Always
#  selector:
#    matchLabels:
#      io.kompose.service: postgres-beak
