name: "Learnin Test Workflow"

on:
  push:

jobs:
  test-job:
    name: "Learnin Test Job"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch a token
        env:
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
        run: ./scripts/learninAuth.py
      - name: Echo token
        env:
          ID_TOKEN: ${{ env.ID_TOKEN }}
        run: echo "${ID_TOKEN}"
      - name: Run HawkScan
        env:
          ID_TOKEN: ${{ env.ID_TOKEN }}
        uses: stackhawk/hawkscan-action@v1.2.1
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
          environmentVariables: ID_TOKEN
          dryRun: true
