name: "HawkScan SARIF Tester"

on:
  push:

jobs:
  test-job:
    name: "HawkScan SARIF Tester"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run HawkScan
        env:
          HAWK_MEM: 3g
          ACTIONS_RUNNER_DEBUG: true
          ACTIONS_STEP_DEBUG: true
        uses: stackhawk/hawkscan-action@4c3258cd62248dac6d9fe91dd8d45928c697dee0
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
#           dryRun: true
          environmentVariables: HAWK_MEM
          configurationFiles: |
            stackhawk-example.yml
          codeScanningAlerts: true
          githubToken: ${{ github.token }}
