name: "HawkScan SARIF Tester"

on:
  push:

jobs:
  test-job:
    name: "HawkScan SARIF Tester"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run HawkScan
        env:
          HAWK_MEM: 3g
          ACTIONS_RUNNER_DEBUG: true
          ACTIONS_STEP_DEBUG: true
        uses: stackhawk/hawkscan-action@feature/sarif-option
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
          environmentVariables: HAWK_MEM
          configurationFiles: |
            stackhawk-example.yml
          codeScanningAlerts: true
          githubToken: ${{ github.token }}
