name: "Teachable Test Workflow"

on:
  push:

jobs:
  test-job:
    name: "Teachable Test Job"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
#      - name: Run HawkScan
#        env:
#          HAWK_MEM: 3g
#        uses: stackhawk/hawkscan-action@v1.2.1
#        with:
#          apiKey: ${{ secrets.HAWK_API_KEY }}
#          environmentVariables: HAWK_MEM
#          image: stackhawk/hawkscan:beta
      - name: Run HawkScan with Normal Docker
        env:
          API_KEY: ${{ secrets.HAWK_API_KEY }}
        run: |
          docker run --tty --rm --volume $(pwd):/hawk --env HAWK_MEM --env API_KEY --network host stackhawk/hawkscan:beta stackhawk.yml
